---
- name: swapfile exists
  stat:
    path: "/swapfile"
  register: swapfile_check

- name: swapfile is created
  command: dd if=/dev/zero of=/swapfile bs=1024 count=3145728
  when: not swapfile_check.stat.exists
  become: yes

- name: swapfile is prepared
  command: mkswap /swapfile
  when: not swapfile_check.stat.exists
  become: yes

- name: swapfile permissions are set
  file:
    path: /swapfile
    mode: "600"
  become: yes

- name: swap is turned on
  command: swapon /swapfile
  when: not swapfile_check.stat.exists
  become: yes

- name: swap configured in fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "/swapfile"
    line: "/swapfile none swap sw 0 0"
  become: yes