---
# See https://metallb.universe.tf/configuration/
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system  
  name: config
data:
  config: |  
    address-pools:
    - name: lb-address-pool 
      protocol: layer2
      addresses:
      - 192.168.0.210-192.168.0.220
 
