---
- name: apt update and upgrade
  apt:
    cache_valid_time: 86400
    update_cache: yes
    upgrade: "yes"
  become: true

- name: default user is removed
  user:
    name: ubuntu
    state: absent
  become: true
