---
- hosts: 127.0.0.1
  tasks:
  - name: apt upgrade
    apt:
      update_cache: yes
      upgrade: dist
    become: true
  - name: pi user is absent
    user:
      name: pi
      state: absent
      force: yes
    become: true
  - name: required apt keys are present
    apt_key:
      url: "{{ item }}"
    with_items:
      - "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      - "https://download.docker.com/linux/debian/gpg"
    become: true
  - name: required apt repos are present
    apt_repository:
      repo: "{{ item }}"
    with_items:
      - "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      - "deb [arch=armhf] https://download.docker.com/linux/debian stretch stable"
    become: true
  - name: required packages are latest
    apt:
      name:
      - vim
      - kubeadm
      state: latest
    become: true
  - name: docker package is supported version
    apt:
      name: docker-ce=18.06.1~ce~3-0~debian
      state: present
    become: true
  - name: docker will not be upgraded
    dpkg_selections:
      name: docker-ce
      selection: hold
    become: true
