---
- hosts: 127.0.0.1
  tasks:
  - name: apt upgrade
    apt:
      update_cache: yes
      upgrade: dist
    become: true
  - name: pi user is absent
    user:
      name: pi
      state: absent
      force: yes
    become: true
  - name: kubernetes apt key is present
    apt_key:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    become: true
  - name: kubernetes apt repo is present
    apt_repository:
      repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    become: true
  - name: kubeadm is latest
    apt:
      name: kubeadm
      state: latest
    become: true
