---
- hosts: 127.0.0.1
  tasks:
  - name: apt upgrade
    apt:
      update_cache: yes
      upgrade: dist
    become: true
  - name: required packages are latest
    apt:
      name:
      - vim
      state: latest
    become: true
