---
- name: kube apt key is present
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  become: true

- name: kube apt repo is present
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  become: true

- name: kubeadm is latest
  apt:
    name: kubeadm
    state: latest
  become: true
