---
- name: cgroups are enabled
  lineinfile:
    backrefs: yes
    line: cgroup_enable=memory cgroup_memory=1 \2
    path: /boot/firmware/cmdline.txt
    regexp: ^(cgroup_enable=memory cgroup_memory=1 )?(.*)$
  become: true
  register: cgroups

- name: reboot to apply cgroup changes
  reboot:
  become: true
  when: cgroups.changed

- name: microk8s is installed
  community.general.snap:
    name: microk8s
    channel: 1.18/stable
    classic: yes
  become: true

- name: dave is member of microk8s
  user:
    name: dave
    groups: [microk8s]
    append: yes
  become: true

- name: join commands generated on controller
  command: microk8s add-node
  register: add_node_output
  when: controller|bool == True
  loop:
  # TODO: Determine automagically
  - pi02
  - pi03

- name: join commands fact is set
  set_fact:
    join_commands: "{{ join_commands|default({}) | combine({item.item: item.stdout | regex_findall('Join node with: (.*)\n') | first}) }}"
    cachable: yes
  when: controller|bool == True
  loop: "{{ add_node_output.results }}"

- name: leafs nodes have been joined to cluster
  command: "{{ hostvars['pi01']['join_commands'][inventory_hostname] }}"
  when: controller|bool == False

- name: metallb is enabled
  command: microk8s enable metallb:192.168.0.210-192.168.0.219
  when: controller|bool == True
